color0  #F5DEB3
color1  #FFD39B
color2  #FFC87C
color3  #FFB85C
color4  #FFA837
color5  #FF8C00
color6  #FF6347
color7  #FF4500
color8  #FF6A4D
color9  #FF7F60
color10 #FF9473
color11 #FFA986
color12 #FFBE99
color13 #FFD3AC
color14 #FFE8BF
color15 #FFF5D2